# This file was *autogenerated* from the file ex6_2.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_6 = Integer(6); _sage_const_0x1 = Integer(0x1); _sage_const_10000 = Integer(10000); _sage_const_10 = Integer(10); _sage_const_0p01 = RealNumber('0.01')#
# Author : Sebastien Duc
#
import sys

def check_business(K):
    profit = _sage_const_0 
    for x in xrange(_sage_const_10000 ):
        p = _sage_const_1 
        while power_mod(_sage_const_2 ,p,p) !=_sage_const_2 :
            p = getrandbits(K) | _sage_const_0x1 
        if (is_prime(p)):
            profit = profit + _sage_const_0p01 
            print "Your profit is : " + str(profit)
        else:
            profit = profit - _sage_const_10 **_sage_const_6 
            print "Your profit is : " + str(profit)
    print "Your profit is : " + str(profit)


if __name__ == "__main__":
    if len(sys.argv) < _sage_const_2 :
        sys.exit("Enter an integer")

    K = Integer(sys.argv[_sage_const_1 ])
    check_business(K)

