# This file was *autogenerated* from the file ex6_1_i.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_1024 = Integer(1024); _sage_const_20 = Integer(20)#
# Author: Sebastien Duc
#
import sys

if __name__ == "__main__":
    if len(sys.argv) < _sage_const_2 :
        sys.exit("Enter a sciper number")

    s = Integer(sys.argv[_sage_const_1 ])

    L = power(_sage_const_2 ,_sage_const_1024 )*s
    U = L + power(_sage_const_2 ,_sage_const_20 )

    primes = []
    p = pari("nextprime("+str(L)+")")
    primes.append(p)
    p = p + _sage_const_1 
    while p < U:
        p = pari("nextprime("+str(p)+")")
        primes.append(p)
        p = p + _sage_const_1 

    print "You have generated " + str(len(primes)) + " primes"

