# This file was *autogenerated* from the file factor.sage.
from sage.all_cmdline import *   # import sage library
_sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)#
# Author: Sebastien Duc
#

import sys

def random1_n(n):
    return Integer(randint(_sage_const_0 ,n-_sage_const_1 )) 

def my_factor(n):
    already_found = [random1_n(n)]
    cI, cII = _sage_const_1 ,_sage_const_0 
    while True:
        same = False
        k = random1_n(n)
        cI += cI 
        for x in already_found:
            # just check if we haven't already picked this number
            if x == k:
                same = True
                print "Duplicate"
                break
            
            d = gcd(x-k,n)
            cII += _sage_const_1 
            if d > _sage_const_1 :
                print "We did " + str(cI) + " calls to black box I"
                print "We did " + str(cII) + " calls to black box II"
                return (d,n/d)

        if not same:
            already_found.append(k)




if __name__ == "__main__":
    if len(sys.argv) < _sage_const_2 :
        sys.exit("Enter an integer")

    n = Integer(sys.argv[_sage_const_1 ])
    print(my_factor(n))

